-- This hand-written SQL reference is retired now that the app runs on MySQL.
-- `prisma/schema.prisma` is the single source of truth for the database schema.
-- To create/update the tables on a fresh database, run:
--   npx prisma db push
-- (or `npx prisma migrate dev` / `npx prisma migrate deploy` if you prefer tracked migrations).
